apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-mrh8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-mrh8
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-mrh8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-mrh8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-mrh8
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kfrr-tenant/rhtap-demo-app/hacbs-test-project-mrh8@sha256:44f159502e039936b79bfa5b3a5ef000672a94d84b8bdcf41c5d804e2482cd7a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
