apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-mrh8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kfrr-tenant/rhtap-demo-app/hacbs-test-project-mrh8@sha256:17575f7c860ef3b49df4dba76bbb67b0f1a3d797d6589950c0f67d25ce941ad7
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
